spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/imrt"

security:
    basic:
      enabled: false

logging:
  level:
    org.opentestsystem: DEBUG

