spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/imrt"
    username: ${IMRT_DB_USER}
    password: ${IMRT_DB_PASSWORD}
  freemarker:
    check-template-location: false

management:
  port: 9008
  security:
    enabled: "false"

logging:
  level:
    org.opentestsystem: DEBUG

openam:
    checkTokenEndpointUrl: https://sso-deployment.sbtds.org/auth/oauth2/tokeninfo

server:
  port: ${IMRT_ISS_SERVER_PORT:9080}
---
spring:
  profiles: local-development
logging:
  config: classpath:log4j2-local.xml
