spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/imrt"


logging:
  level:
    org.opentestsystem: INFO

openam:
    checkTokenEndpointUrl: https://sso-deployment.sbtds.org/auth/oauth2/tokeninfo

server:
  port: ${IMRT_ISS_SERVER_PORT:9080}
---
spring:
  profiles: local-development
logging:
  config: classpath:log4j2-local.xml
